### ISSUE TITLE
Incomplete API docs

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/runciv#17]
The endpoint [POST /api/v2/lobbies](https://runciv.hopfenspace.org/docs/#/Lobbies/create_lobby) has incomplete API docs. Please extend and finish them. :)

Edit: Besides, could you also add a short notice when endpoints trigger WebSocket events and to whom? E.g. for `PUT /api/v2/games/{uuid}`, add a notice about `UpdateGameData` events and who might receive them.
For future documentation purposes, [AsyncAPI](https://www.asyncapi.com/) might be a good thing for the WebSocket documentation. I don't know how good that is supported by Rust frameworks, though.

**Comment by myOmikron** [comment]
I don't think adding yet another API definition framework will give as a benefit. 

We are only invoking notification events via websocket, that should be rather self-explanatory
