### ISSUE TITLE
Yet another non-deterministic internal server error

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/runciv#22]
`'GET https://runciv.hopfenspace.org/api/v2/games/fcea6e5c-8967-4d1d-8040-bc2569ac3be2': 500 Internal Server Error (38 ms): DatabaseError`

Actually expecting a `GameNotFound` response. How to reproduce:

1. Login with a valid user
2. Use the `GET /api/v2/games/{uuid}` endpoint with some random UUID.
3. Sometimes it works, sometimes it throws DB errors.

The newer version of rorm should have fixed that already, if it's related to the issue there.

**Comment by myOmikron** [comment]
There isn't a new version of rorm yet

**Comment by myOmikron** [comment]
Server is updated to new version, if the problem persists, feel free to open this issue again
