### ISSUE TITLE
When the owner of a lobby disconnects (WebSocket close), the lobby should be closed

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/runciv#27]

**Comment by CrsiX** [comment]
It think it's not working properly. I open a lobby, one other player joins in. The owner disconnects (`[DEBUG | runciv::server::handler::websocket] Websocket closed` in the server logs). But:
- the lobby is still open (lobby list)
- chatting is still possible in the lobby chat room
- users can still join the lobby, and the others receive correct WS updates (e.g. `LobbyJoin` event)
- the owner of the lobby is disconnected, but when reconnecting, it can join a new lobby (has it been removed from the lobby list?)

Note that I don't read `Closed websocket due to missing heartbeat responses` or `Client closed websocket` or `Closing lobby {} due to missing ws connection of owner {uuid}` in the server logs, since the client game didn't _crash_, it _exited properly_ by sending a WebSocket close control message.

Also note that I can read

```
[ERROR | runciv::chan::ws_manager_chan] Error sending to client: Mailbox has closed, closing socket
[ERROR | runciv::chan::ws_manager_chan] Error closing socket: Mailbox has closed
```

in the server logs whenever I send a text message to the lobby chat, i.e. the server still tries to send WS events to the owner of the lobby?

It also doesn't work for lobby members other than the owner.

**Update:**
Even if the network is interrupted (no properly closed WebSocket in the logs), it fails to close the lobby. I can read a bunch of `ICMP unreachable` answers in the network dump, but still no server logs that the WebSocket was closed by one of the newly added features.
Instead, I have the following log entry (for network-related close only):

```
[INFO  | requests] 192.168.160.215 "GET /api/v2/ws HTTP/1.1" 101 2082 "-" "Unciv/4.6.5 (Build 855)-GNU-Terry-Pratchett" 390.051938
[DEBUG | runciv::server::handler::websocket] Closed websocket due to missing heartbeat responses
[DEBUG | rorm_db::database] SQL: SELECT "lobby"."uuid", "lobby"."name", "lobby"."owner", "lobby"."password_hash", "lobby"."max_player", "lobby"."chat_room", "lobby"."created_at" FROM "lobby" JOIN "lobby" AS lobbyaccount__lobby ON ("lobbyaccount__lobby".uuid = "lobbyaccount".lobby) WHERE ("lobbyaccount__lobby".owner = $1) LIMIT 1;
[ERROR | runciv::chan::ws_manager_chan] Database error: sqlx error: error returned from database: missing FROM-clause entry for table "lobbyaccount"

```

**Comment by myOmikron** [comment]
Seems to work now
